environment:
  major: 3
  minor: 1
  patch: 0

version: $(major).$(minor).$(patch)+{branch}-{build}

image: Visual Studio 2017
configuration: Release    

dotnet_csproj:
  patch: true
  version: $(major).$(minor).$(patch)
  file: src\Serilog.Sinks.TestCorrelator\Serilog.Sinks.TestCorrelator.csproj

before_build:
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  - provider: NuGet
    api_key:
      secure: 540voj1txXVEVd5Y9aHMqHFEzK4FFTCPz4FSc2d/U2hU5iQ69PIQFbr5PjZalBN6
    skip_symbols: false
    on:
      branch: master