environment:
  major: 3
  minor: 0
  patch: 2

version: $(major).$(minor).$(patch)+{branch}-{build}

image: Visual Studio 2017
configuration: Release    

dotnet_csproj:
  patch: true
  version: $(major).$(minor).$(patch)
  file: src\Serilog.Sinks.TestCorrelator\Serilog.Sinks.TestCorrelator.csproj

before_build:
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
  - provider: NuGet
    api_key:
      secure: nrvEl2qb2BnEzXO8I3wdMRCawAa8hMpiVbmNBciLPagEaBmeJyA5yM4Ntdj7M0To
    skip_symbols: false
    on:
      branch: master