version: '2.0.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- 'dotnet restore'
build_script:
- 'dotnet build /p:Version={version}'
artifacts:
- path: '**\*.nupkg'
test_script:
- 'dotnet test .\test\serilog-utilities-concurrent-correlator-tests\Serilog.Utilities.ConcurrentCorrelator.Tests.csproj --no-build'
deploy:
- provider: NuGet
  api_key:
    secure: nrvEl2qb2BnEzXO8I3wdMRCawAa8hMpiVbmNBciLPagEaBmeJyA5yM4Ntdj7M0To
  on:
    branch: master