environment:
  major: 3
  minor: 0
  patch: 0

image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  version: '{version}'
  file: src\Serilog.Sinks.TestCorrelator\Serilog.Sinks.TestCorrelator.csproj

before_build:
 - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

for:
  - branches:
      except:
        - master
    version: $(major).$(minor).$(patch)+{branch}-{build}
  
  - branches:
      only:
        - master
    version: $(major).$(minor).$(patch)
    deploy:
      - provider: NuGet
        api_key:
          secure: nrvEl2qb2BnEzXO8I3wdMRCawAa8hMpiVbmNBciLPagEaBmeJyA5yM4Ntdj7M0To
        skip_symbols: false