version: '2.0.0.{build}'
image: Visual Studio 2017
platform: Any CPU
before_build:
- dotnet restore
build_script:
- dotnet build .\src\SerilogTestCorrelation\SerilogTestCorrelation.csproj /property:Configuration=Release /property:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
test_script:
- dotnet test .\test\SerilogTestCorrelation.Tests\SerilogTestCorrelation.Tests.csproj /property:Configuration=Release
deploy:
- provider: NuGet
  api_key:
    secure: nrvEl2qb2BnEzXO8I3wdMRCawAa8hMpiVbmNBciLPagEaBmeJyA5yM4Ntdj7M0To
  on:
    branch: master